### ISSUE TITLE
PublicAccessNotPermitted

### ISSUE THREAD

**Issue by Postur** [SierraSoftworks/markout#1026]
The URL https://[markout.sierrasoftworks.com/outlook/manifest.xml](https://markout.sierrasoftworks.com/outlook/manifest.xml)

Gives a PublicAccessNotPermitted Error.

This is what I get from the website:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>PublicAccessNotPermitted</Code>
<Message>Public access is not permitted on this storage account. RequestId:d50046a2-c01e-003f-0157-f8e21a000000 Time:2023-10-06T13:16:50.5140163Z</Message>
</Error>
```

**Comment by notheotherben** [comment]
Sorry about that, change of default policies on the Azure side - this should now be resolved.
